version: '2'
services:
  rest:
    build: ./rest/src/catcierge-rest
    ports:
     - "8080:8080"
     - "5000:5000"
    volumes:
     - ./rest/src:/go/src/app
    depends_on:
     - mongo
    environment:
     - MONGO_URL=mongodb://mongo:27017
  mongo:
    image: mongo
    ports:
     - "27017:27017"
  # TODO: Add web docker (polymer)
