version: '2'
services:
  rest:
    build: ./rest
    ports:
     - "8080:8080"
     - "5000:5000"
    volumes:
     - ./rest:/go/src/app
  #  depends_on:
  #   - mongo
  #mongo:
  #  image: mongo
  # TODO: Add web docker (polymer)
